### ISSUE TITLE
Delete all playlists before importing

### ISSUE THREAD

**Issue by apoapostolov** [JacobMcAuley/playlist_import#10]
As an alternative to #9 add an option that deletes all existing playlist folders before importing. This allows maintaining a clean slate before importing each new instance of the music directory.

**Comment by JacobMcAuley** [comment]
This one I can do!
I'm currently working on another project, so you'll need to wait for that to finish; however, I will mark this as a an enhancement and add it in a future patch.

**Comment by DrYoshiyahu** [comment]
Yeah, this is also important because it will delete songs from Foundry that have been deleted in the data folder structure.

EDIT: Never mind the fact that it will allow new playlists to be slotted into alphabetical order.

**Comment by DrYoshiyahu** [comment]
In the meantime, while we wait for an update, @apoapostolov, this simple macro will delete all the playlists.

`for (const i of game.playlists)    await i.delete();`

I just set this up as a button on my hotbar to press whenever I want to update my playlists.

**Comment by apoapostolov** [comment]
Thank you!
