### ISSUE TITLE
[Feature request] Add multilanguage support

### ISSUE THREAD

**Issue by lozalojo** [JacobMcAuley/playlist_import#18]
Please add the framework for translating the module to other languages (as other modules do, with an en.json file in a lang folder with keys that we can translate).

I have translated more than 10 modules and this one doesnt support translating.

Thanks and great work!

**Comment by JacobMcAuley** [comment]
Hi, @lozalojo! 

You've caught me redhanded. I should've done this much earlier. I've set up the traditional lang folder with the initial en.json file if you would like to translate it into another language or languages! It's super likely that I missed a key or two when trying to convert it into a .json file, so if you happen to catch anything just open another issue and I'll adjust it when I get the chance. 

Thanks for point this out! 
Jacob

**Comment by lozalojo** [comment]
Sure, I will translate it to Spanish as soon as possible and report missing keys.

Thank you!

**Comment by lozalojo** [comment]
I sent you a PR for spanish, thou there is a bug with translation, reported here:

https://github.com/JacobMcAuley/playlist_import/issues/20
