### ISSUE TITLE
[Bug] Translation implementation broke setup

### ISSUE THREAD

**Issue by lozalojo** [JacobMcAuley/playlist_import#20]
Here it is:

Core 0.6.6
Playlist importer 1.5.1
Language set to english:

![](https://i.ibb.co/TP2JzxJ/screenshot-208.jpg)

**Comment by JacobMcAuley** [comment]
You did it for me! Thank you again.

EDIT: I misread! It was someone else, submitted the fix! Thank you for bringing it to their attention though!

**Comment by lozalojo** [comment]
Seems that it does not apply translated keys, I set language to Spanish and it is still in English.

**Comment by jlanatta** [comment]
@lozalojo The file for Spanish has the same problem as the file for English used to have. Feel free to submit a PR with the fix, otherwise I can fix it later or I guess @JacobMcAuley can do it on his next version.

**Comment by lozalojo** [comment]
I saw no diferences, let me check!

**Comment by lozalojo** [comment]
Ops, an additional comma at the end!

**Comment by lozalojo** [comment]
Sent PR with the Fix

Also, seems that PLI.LogvolumeHint key has a typo since it doesnt get translated, I assume It is the same in english

**Comment by lozalojo** [comment]
Ok, it is PLI.LogVolumeHint, capital V, I fixed in en.json file also. Sent PR

**Comment by JacobMcAuley** [comment]
Ah, this is what I get for not being careful with spelling! 
I'll wait until I get to a workstation this time around so I can do a quick review before I accept the PR.

**Comment by JacobMcAuley** [comment]
Thanks for being patient, it was my sisters birthday!
I looked over the submitted PR and it looked like you caught it. Hopefully it all works out.
