### ISSUE TITLE
Not working after importing a couple of folders

### ISSUE THREAD

**Issue by TheProfessor757** [JacobMcAuley/playlist_import#24]
I have a bunch of audio folders in the "MP3" folder of "Data". I am using Forge to host my game as well.
It will import and populate two or three playlists from the MP3 folder and then stop leaving the rest of the playlists imported but completely unpopulated. 
All files are in MP3 formate and uniquely named.

**Comment by TheProfessor757** [comment]
Figured it out:
Have to sit here and babysit it, opening each playlist as they populate and closing the previous one.
Lotsa fun.

**Comment by JacobMcAuley** [comment]
Hi, @TheProfessor757.
Thanks for the report! I've attempted to recreate the issue, but I'm having some issues. If you wouldn't mind helping out a bit with some more details that would be awesome! If you could attach some pictures of your playlist importer settings and your audio browser like below, that would be instrumental in making your future uses much easier!

Thanks!
![img](https://user-images.githubusercontent.com/12160735/102300427-c6f2f980-3f09-11eb-8bac-67176ac4fe71.png)
![img2](https://user-images.githubusercontent.com/12160735/102300434-cd817100-3f09-11eb-9a13-4e83a3074c5e.png)

**Comment by TheProfessor757** [comment]
Hi Jacob!
It works for me fine now.
I just have so many folders that it takes a long time, and the process gets
interrupted if I navigate away from the page in The Forge.
I would chalk this up to operator error at this point

Thanks for reaching out!
-Prof

**Comment by JacobMcAuley** [comment]
Awesome! I'm happy to hear it.
May your campaign be filled with music! :smile: 
- Jacob
