### ISSUE TITLE
Cannot import playlists from folders within data

### ISSUE THREAD

**Issue by ppepin34** [JacobMcAuley/playlist_import#26]
I am unable to upload playlists from folders located within my data folder.  Attached is a screenshot of the error 
![image](https://user-images.githubusercontent.com/59454905/103142502-125b9380-46d2-11eb-907f-118a0743b2f5.png)

**Comment by JacobMcAuley** [comment]
Hi Ppepin,
If you submit a picture of your filestructure as well, I would be able to help out more.
Unfortunately, the only thing I can ascertain from this is that the folder you're attempting to import from seems to be non-existant from the eyes of the program.
Some generic tips are to:
1. Make sure your folder is properly named
2. Make sure that you're requesting imports from the proper directory.
3. Make sure the playlists are in the proper format.
4. Make sure your music folder is actually located within the 'data' category.

If the generic tips don't worry feel free to reopen and I'll help you through it.
