### ISSUE TITLE
Update settings-extender.js for 0.5.4 compatibility

### ISSUE THREAD

**Issue by JiDW** [JacobMcAuley/playlist_import#3]
the settings-extender module needs to be updated to its latest release in order to not break the config settings in 0.5.4

See https://gitlab.com/foundry-azzurite/settings-extender/-/issues/3

Thanks!

**Comment by JacobMcAuley** [comment]
You're absolutely right, thanks for pointing that out. I've updated it to reflect the changes in 0.5.4.
Happy gaming!
