### ISSUE TITLE
Stopped working with Foundry VTT 0.8.6

### ISSUE THREAD

**Issue by TylerKing156** [JacobMcAuley/playlist_import#35]
Importer was working great with version 0.7.10. After updating to Foundry 0.8.6, it is no longer functioning. 

Nothing happens after clicking on "Begin Import".

Hosted locally.

**Comment by JacobMcAuley** [comment]
Hi Tyler,

I'm going to need a bit more information. I'm testing on v0.8.8, but from my testing it still works on my end. I imported music locally and not from an S3 Bucket.
For now, I'm going to close the issue. Feel free to reopen it with attachments detailing the issue.
