### ISSUE TITLE
The directory picker for the 'Base Music Folder' not work

### ISSUE THREAD

**Issue by p4535992** [JacobMcAuley/playlist_import#37]
**Describe the bug**
The Directorypicker used on the form settings for get the path of the "folder dirs root", it's not working it's keep telling me:

`
Uncaught (in promise) Directory [object Object] does not exist or is not accessible in this storage location
`

**To Reproduce**
1. Go to 'Module settings' of the module
2. Click on the Directory picker of the 'Base Music Directory' 
3. You can already see the value '[object Object]' and you can't change the value because it' still go to the value '[object Object]' .
![img](https://i.imgur.com/mfYu6lJ.png)
4. I debugged the code and change the string '[object Object]' with the path to the directory and all it is work fine

**Expected behavior**

I want when i selected the folder with the picker on the path data/mymusic to see the string 'data/mymusic'  on the 'path' variable at the line of code 
https://github.com/JacobMcAuley/playlist_import/blob/master/src/main.js#L381

**Screenshots**

![img](https://i.imgur.com/mfYu6lJ.png)

**Desktop (please complete the following information):**

Foundry VTT Version: 0.8.8

Operating System: [Linux], [Window]

How Are You Using Foundry: [Linux,Native Application (Electron), Chrome], [Window,Native Application (Electron), Chrome]

Which Game System: Dungeons and Dragons 5th Edition, version 1.3.6

Modules Enabled?: yes

Module version: 1.6.1

OS, Hosting, Browser (if applicable): Linux/Node/Chrome

**Additional context**

**Comment by JacobMcAuley** [comment]
Hi @p4535992 ,

Thanks for the detailed report. I've attempted to reproduce your issue; however, I'm not quite able to get it to display the error you're experiencing. I've attached a gif showing what I tried. 

![Example](https://user-images.githubusercontent.com/12160735/123554674-eaf38b00-d735-11eb-9d56-5420fcb331af.gif)

**Comment by p4535992** [comment]
mmm strange,  well  i close the issue than , ty for your time!
