### ISSUE TITLE
Playlist Importer will not save Directory

### ISSUE THREAD

**Issue by cvanhouten35** [JacobMcAuley/playlist_import#39]
name: Bug report
about: 
title: ''
labels: ''
assignees: ''

---

**Describe the bug**
Playlist Importer will not save or import from directory.

**To Reproduce**
1. Go to "Module Settings"
2. Select appropriate directory with organized folders of music within.
3. Click Save Changes and window closes
4.  Click the "Playlist Import" button on the playlist tab and then "Begin Import"
5. Window closes and nothing happens.
6. Go back and check the "Module Settings" tab in "Configure Game Settings" to find that the "Base Music Directory" has been switched to "[object Object]"

**Expected behavior**
For the Playlist importer to pull from the selected Directory and start importing when prompted.

**Screenshots**
![image](https://user-images.githubusercontent.com/59463137/126704507-32047fbc-c5b7-4a6e-aed7-48060e5a66ac.png)
![image](https://user-images.githubusercontent.com/59463137/126704468-1ba5a814-fa34-4a0f-b9ef-0f1d3e8ef3d7.png)
![image](https://user-images.githubusercontent.com/59463137/126704403-664c47a6-01ed-4b7f-a0a5-1291bbbf5c22.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Foundry 0.8.8

**Comment by Tupsi** [comment]
I can confirm that this isn't working on linux neither.

**Comment by JacobMcAuley** [comment]
Should be resolved with the most recent update! Thanks for the heads up
