### ISSUE TITLE
playlist_import preventing 'Configure Settings' window to open with FoundryVTT 0.5.5

### ISSUE THREAD

**Issue by yjeroen** [JacobMcAuley/playlist_import#4]
**Describe the bug**
playlist_import preventing 'Configure Settings' window to open with FoundryVTT

**To Reproduce**
1. Go to 'Settings' tab
2. Click on 'Configure Settings'
3. Check console errors

**Comment by JacobMcAuley** [comment]
Thanks for the issue report! This looks to me like a duplicate report of [settings-extender.js](https://github.com/JacobMcAuley/playlist_import/issues/3). This should resolve the issue!
