### ISSUE TITLE
Manifest URL Issue

### ISSUE THREAD

**Issue by DrYoshiyahu** [JacobMcAuley/playlist_import#40]
Whenever I try to update the module through Foundry, I'm getting this popup saying the Manifest URL has changed, but even when I click yes, the popup still appears the next time I try to update.

![image](https://user-images.githubusercontent.com/14756430/128960434-6d2468c7-f7ce-49af-9779-4d4b123405bc.png)

It goes through the motions of a progress bar, and then gives this success popup, but rest assured, if I click the update button again, I'll get the same Manifest URL popup.

![image](https://user-images.githubusercontent.com/14756430/128960599-e71e2a85-709d-45a2-8786-bf866e7ed431.png)

**Comment by JacobMcAuley** [comment]
Good news, 
You do have the most recent version of the module. I just made a mistake in typing the version number when uploading it to Foundry. I've fixed the version number (1.7.0) and you shouldn't receive the notification anymore.
