### ISSUE TITLE
only imports the names of the folders

### ISSUE THREAD

**Issue by cnutenor** [JacobMcAuley/playlist_import#41]
**To Reproduce**
Currently I have the structure "media/audio/" and the importer only imports the names of the folders leaving the playlists empty.

**Expected behavior**
It would be amazing if you could allow the module to import music up to 2-level deep folders.

**Comment by CifCafat** [comment]
I have the same issue, but it worked a week ago. Songs no longer get imported but only the file name. However this only effects one Game World I'm in, in the rest it works despite everything (settings, modules, system) being the same.

I tried reinstalling the mod, restarting Foundry, changing directories, nothing worked. I repeat, the same settings are present in an identical game world, and that one doesn't have an issue.

It also does not import in 1 level deep folders for me, it seems to just ignore any music files.

**Comment by zdaar** [comment]
I have the same issue

EDIT : I fixed it by going to settings and using "Playlist-Importer Memory Clear", and reimporting.
