### ISSUE TITLE
Doesn't seem to work, maybe a v9 thing?

### ISSUE THREAD

**Issue by Nuku** [JacobMcAuley/playlist_import#43]
Attempting to import gets a 0/x playlists imported. Nothing happens. Tried clearing the memory, still nothing. x is equal to the number of folders, so it sees the folders. With V9 on Windows.

**Comment by jtpjr** [comment]
I am having the same issue, seen here:
![image](https://user-images.githubusercontent.com/31330365/148746999-5e8c9830-6559-4a6a-9167-a6efe4c052df.png)

The structure of this folder follows that of the readme, I think there's an issue with the module

**Comment by JacobMcAuley** [comment]
Fixed!
