### ISSUE TITLE
[BUG] No Import Playlist Button

### ISSUE THREAD

**Issue by pesky-wobbit** [JacobMcAuley/playlist_import#49]
**Module Version:** v1.7.3

**Describe the bug**
Import Playlist button just isn't there.

**To Reproduce**
1. I've enabled the module
2. Click the playlist tab.
3. No button.

**Expected behavior**
I hope to see the button

**Browser:**
Chrome

**Foundry Version:** 
9.251

**Game System:** 
dnd5e

**Additional context**
I tried disabling Blitz's Soundboard to no effect.

**Comment by p4535992** [comment]
Seem to work on my dnd5e world .
![img](https://i.imgur.com/SUmJipS.png)
tested with "Blitz's Soundboard" active and inactive.

Any error on the web console (any red message if you click F12 on the browser) ?

**Comment by pesky-wobbit** [comment]
No errors on console. I understand it's hard to troubleshoot if you can't
recreate it. I'll try creating a dummy world and see if the buttons pop up.
Thanks!

**Comment by pesky-wobbit** [comment]
With all modules disabled (but playlist importer) the buttons DO appear.
I'll let you know if I find the conflicting module.

**Comment by pesky-wobbit** [comment]
Music Permissions

**Comment by p4535992** [comment]
I will look into to it!! ty for the contribution

**Comment by Matthew-Whitlock** [comment]
This should be solved as of Music Permissions v2.0.2 - thanks for reporting it and sorry for the wait!
