### ISSUE TITLE
Playlist Import places `%20` in playlist names instead of spaces

### ISSUE THREAD

**Issue by Sciguymjm** [JacobMcAuley/playlist_import#5]
**Describe the bug**
Playlist Import places `%20` in playlist names instead of spaces.

**To Reproduce**
1. Go to VTT Music.
2. Click on Playlist import.
3. Wait for import of playlist with spaces in name.

**Expected behavior**
Spaces should not be encoded.

**Screenshots**
![chrome_2020-04-23_14-28-19](https://user-images.githubusercontent.com/1396015/80136421-a982b100-856f-11ea-8364-e307e7a84006.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
Could be due to the recent update of Foundry or another module. Bug hunting ideas would be appreciated.

**Comment by JacobMcAuley** [comment]
Originally, if I remember correctly, spaces in directory names caused issues in general when it came to foundry pathing. This might've been changed, so I'll look into it. However, as a precaution, I generally advise against having spaces in directory names. I'll look a little deeper before I close the issue though! Thanks for the thorough bug report.

**Comment by Sciguymjm** [comment]
Great! Thanks for the heads up. If I can figure out how to debug modules I can figure out what's happening. Like I said it imported properly before, it was just recently that this changed.

**Comment by JacobMcAuley** [comment]
Updated and fixed! Hopefully the %20 should show up as a space now. If you happen to notice anything else in the future please don't hesitate to let me know!

**Comment by Sciguymjm** [comment]
Looks like it works! Thanks so much.
