### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TheWoodenMan** [JacobMcAuley/playlist_import#50]
**Foundry v9**
**Pathfinder 2e v3.7.1.10801**

**Module Version:** v1.7.3

**Describe the bug**
Clicking "import playlist" doesn't import any of the directories into a playlist.
Number of playlists imported shows as /24

**To Reproduce**
1. Go to the playlist tab
2. Click on "Import Playlist"
3. click on "begin import" on the pop-up.
4. Dialogue box pops up with "0/0 operation completed" very quickly and self-closes.
5. "Playlist importer has completed it's task" pops up - Click "tick" 
7. Number of playlists completed /24 pops up
8. ![image](https://user-images.githubusercontent.com/85075266/158247909-af7d1445-d7d8-44e0-97ff-de0dc448da9c.png)

No new playlists are seen in the playlist tab.

**Expected behavior**
each of the directories should be represented by a playlist folder with tracks listed in each.

**Screenshots**

**Browser:**
 - Chrome

**Foundry Version:** 

**Game System:** 
Pathfinder 2e

**Additional context**
I disabled playlist expander to make sure this isn't interfering with the module but it's the same either way.

if you click the button with the console open, there is an error message:
![image](https://user-images.githubusercontent.com/85075266/158248987-2b5d0546-e407-4208-9fdf-240123554b9c.png)

Which points to this section of code:

`// let finishedDirs = 0;
      //$('#total_playlists').html((localDirs.length));
      let dirName = resp.target;
      let playlistName = PlaylistImporter._convertToUserFriendly(PlaylistImporter._getBaseName(dirName));
      let dirNameCustom = dirNameParent ? dirNameParent + '_' + playlistName : playlistName;
      if (game.settings.get(PLIMP.MODULENAME, 'maintainOriginalFolderName')) {
        dirNameCustom = playlistName;
      }
      let myPlaylists = game.playlists.contents.filter((p) => p.name === dirNameCustom) || [];
      let myPlaylistExists = myPlaylists.length > 0 ? true : false;
      if (myPlaylistExists) {
        **dirNameCustom = dirNameCustom + '-' + myPlaylist.length;**
      }`

Specifically this part where it says myPlaylist is not defined, should it be myPlaylists ?

`dirNameCustom = dirNameCustom + '-' + myPlaylist.length;`

**Comment by TheWoodenMan** [comment]
Disabling all modules then reactivating playlist importer fixes the issue of visibility and all tracks and playlists are now visible, but none of the tracks play when clicked on - I suspect there may be some interference from another module. I'll do some testing and post if I find anything further.

**Comment by TheWoodenMan** [comment]
Deleting all the playlists then re-importing them with only playlist importer installed, (but no other mods) worked, all the playslists are in place and working now.

**Comment by p4535992** [comment]
Try out 1.7.4 and let me know if you encounter the same error

**Comment by KellethDregar** [comment]
Still seem to be encountering the error after 1.7.4

![image](https://user-images.githubusercontent.com/79947702/159143117-729291e7-72c0-4570-9d87-e5a0c07d70b1.png)

**Comment by p4535992** [comment]
The dialog problem is mentioned on the knows issues paragraph:

_The dialog need some very adjustament, for now just ignore whart you see, for lack of the time on developer side, anyone is welcome to open a PR with a loading dialog._

but the "playlist" typo it's now solved.

**Comment by TheWoodenMan** [comment]
Thanks, in any case I got it all working again with the workaround. 
It's a great module, appreciate the work.
