### ISSUE TITLE
Allow songs to be in multiple playlists

### ISSUE THREAD

**Issue by Sciguymjm** [JacobMcAuley/playlist_import#6]
I have songs that belong to multiple playlists and with the current duplicate checking it only adds the songs to one playlist.

https://github.com/JacobMcAuley/playlist_import/blob/master/src/main.js#L105-L110

Instead of `trackName` in the HashMap being the track, if this option is enabled it should also include the playlist/folder name in the hashed name.

**Comment by JacobMcAuley** [comment]
Doh! I can't believe I didn't consider that. This solution makes much more sense. I've updated the way the HashMap works to reflect this reasoning. Thanks for the invaluable input!
