### ISSUE TITLE
Allow importing songs with different options than default

### ISSUE THREAD

**Issue by Sciguymjm** [JacobMcAuley/playlist_import#7]
https://github.com/JacobMcAuley/playlist_import/blob/master/src/main.js#L114

Right now the defaults are `repeat: true, lvolume: 0.5` of which both defaults should be able to be changed (or even just repeat since that's what is available during sound creation normally).

**Comment by JacobMcAuley** [comment]
Another great idea!
It's been updated to reflect the changes. Thanks for the suggestion!
